/*
 * Copyright 2026 Zeppelin Bend Pty Ltd
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package com.zepben.ewb.database.sql.cim.tables.extensions.iec61968.common

import com.zepben.ewb.database.sql.common.tables.Column
import com.zepben.ewb.database.sql.common.tables.Column.Nullable.NOT_NULL
import com.zepben.ewb.database.sql.common.tables.Column.Nullable.NULL
import com.zepben.ewb.database.sql.common.tables.Column.Type.BOOLEAN
import com.zepben.ewb.database.sql.common.tables.Column.Type.STRING
import com.zepben.ewb.database.sql.common.tables.SqlTable

/**
 * A class representing the `ContactDetails` columns required for the database table.
 *
 * @property ID The identifier for this contact, could be autogenerated.
 * @property CONTACT_TYPE The type of contact, e.g. Account Owner.
 * @property FIRST_NAME The first name of the contact.
 * @property LAST_NAME The last name of the contact.
 * @property PREFERRED_CONTACT_METHOD The preferred contact method for this contact.
 * @property IS_PRIMARY Whether this contact is a primary contact.
 * @property BUSINESS_NAME The business name of this contact.
 */
@Suppress("PropertyName")
abstract class TableContactDetails : SqlTable() {

    val ID: Column = Column(++columnIndex, "id", STRING, NOT_NULL)
    val CONTACT_TYPE: Column = Column(++columnIndex, "contact_type", STRING, NULL)
    val FIRST_NAME: Column = Column(++columnIndex, "first_name", STRING, NULL)
    val LAST_NAME: Column = Column(++columnIndex, "last_name", STRING, NULL)
    val PREFERRED_CONTACT_METHOD: Column = Column(++columnIndex, "preferred_contact_method", STRING, NULL)
    val IS_PRIMARY: Column = Column(++columnIndex, "is_primary", BOOLEAN, NULL)
    val BUSINESS_NAME: Column = Column(++columnIndex, "business_name", STRING, NULL)

    init {
        addUniqueIndexes(
            listOf(ID)
        )
    }

}
